[env:m5stack-atoms3r]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

lib_deps =
    m5stack/M5Unified@^0.2.2
    h2zero/NimBLE-Arduino@^1.4.1

build_flags =
    -DCONFIG_NIMBLE_ENABLED=1
    -DARDUINO_M5Stack_ATOM
    -std=gnu++17

build_unflags =
    -std=gnu++11
